### ISSUE TITLE
Data upload

### ISSUE THREAD

**Issue by ChriKu1** [biomedbigdata/namco#31]
Hi there,

I have problems with the data upload. 

It always tells me that the upload of the dataset (ASV/taxonomy/metadata table) is finished, but then the "generating data" step starts and runs forever. I already tried it with different datasets but it still does not work. I formatted the files like described on the website. Is this a known issue?

I would highly appreciate it if you could help me to solve this problem. :)

Thank you!
Christina

**Comment by alex-d13** [comment]
Hi Christina,

Thank you for reaching out :)

You can compare your files with our example data files, which are located here: https://github.com/biomedbigdata/namco/tree/master/app/R/testdata
Maybe our description is not detailed enough.

If you feel like they look the same, I would suggest that you provide the files you are trying to upload to me, so I can check what is going on. 

Best,
Alex

**Comment by ChriKu1** [comment]
Hi Alex,

thank you for the quick reply. :)

Is there a way to write you a pn? I don't want to upload my unpublished data here. ;)

Best,
Christina

**Comment by alex-d13** [comment]
Hi,

Please contact me here: alex.dietrich@tum.de 

Best,
Alex

**Comment by alex-d13** [comment]
Hi Christina,

I found and fixed the bug that caused your issues. Please check again and let me know if you still have issues with uploading your dataset :)

Best,
Alex

(Tagging the commit here: 74fa7ea366648f12a457b296f6e1fe339e31a8c6 )
