### ISSUE TITLE
Error when splitting by group in Taxonomic Binning

### ISSUE THREAD

**Issue by CD4655** [biomedbigdata/namco#32]
Splitting by groups in taxonomic binning is no longer possible without errors. A single data bar appears with the relative abundance and the group name of the selected group. This does not apply to splitting by SampleID. However, the problem does not affect other analysis tools such as Alpha-diversity or Beta-diversity.

**Comment by alex-d13** [comment]
Hi,
Should be fixed now, please let me know if there are still issues with this functionality.
