### ISSUE TITLE
Unable to save session and view data after analysis is complete

### ISSUE THREAD

**Issue by gowdamanv** [biomedbigdata/namco#34]
1. Unable to save the session, the icon is not accessible. 
2. Once the analysis is successful, the entire window becomes unaccessible. Not able to view the results. Tried several times, but this was happening all the time.

**Comment by VeronikaEngelsberger** [comment]
Unfortunately I have exactly the same problem...After uploading my raw fastaq files, I can´t save the session or proceed with further analysis.

**Comment by alex-d13** [comment]
Hi,

could you maybe send me a subset of your fastq files (and meta-data), so I can take a look at this myself?
You can also reach me via email, if you dont want to post the files here: alex.dietrich@tum.de 

Best,
Alex

**Comment by alex-d13** [comment]
Bug was resolved in email conversation with @VeronikaEngelsberger
