### ISSUE TITLE
Couldn't upload .fastq.gz files

### ISSUE THREAD

**Issue by tmuneeswaran** [biomedbigdata/namco#41]
I tried to upload raw sequences. I have .fastq.gz  files in my system. While try to analyse the sequences via upload raw sequences, the files are not selected via uploader. I have tried with safari browser in MacBook Air. The maximum size of the file is 15MB. Kindly resolve this issue

**Comment by lonman99** [comment]
Allowed formats include zipped fastqs and the size should also not be a problem. Could you send us a screenshot of your upload?
