### ISSUE TITLE
DataTables warning: table id=DataTables_Table_1 - Ajax error.

### ISSUE THREAD

**Issue by PumaSocke** [biomedbigdata/namco#44]
Hi

while using Namco an error appeared while uploading raw fastq.gz files. I already uploaded two different datasets and no issues occurred.

I used this dataset: https://www.ebi.ac.uk/ena/browser/view/PRJNA436876 
and renamed the files after the following scheme: SRR6812004_L001_R1_001/SRR6812004_L001_R2_001. As used in Illumina naming conventions resulting in 30 compressed fastq files.

I used the DADA2 Pipeline and generated QC Plots as recommended  and selected the truncation based on the Plot. As with the other Datasets the forward primer with 19 and reverse primer with 20 nucleotides were chosen.

For truncation forward 260 was chosen as a cut off value and 280 for truncation reverse.
After running through the different stages of the pipeline, it switched immediately to another loading screen saying “generating data” and no results were accessible.

One Error message was shown: 

DataTables warning: table id=DataTables_Table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I hope you could help me fix the problem, as I would like to continue working in Namco.

Best Wishes

Asiri

**Comment by lonman99** [comment]
Hello Asiri,

Sorry for the late reply. We fixed the problem and will update the website within the next few days. Please get back to us if you still encounter any problems regarding this issue.

Best
Leon
