### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by PumaSocke** [biomedbigdata/namco#45]
Hi, when oppening the website the following Error message occurs:

"Error
Status code: 500

Message: Failed to start container"

![image](https://user-images.githubusercontent.com/131784966/235110449-983b6e25-d7be-490d-acbd-a96e6dd6fad5.png)

accessed from:
 - Chrome
 - Version 112.0.5615.138

Thank you very much  for helping me fix the problem, as I would like to continue working in Namco

**Comment by alex-d13** [comment]
Hi,

I quickly restarted the app, it should work now :)
Please let us know if you do still have issues.

Cheers,
Alex

**Comment by PumaSocke** [comment]
Hey, thanks a lot
