### ISSUE TITLE
invalid 'row.names' length

### ISSUE THREAD

**Issue by silvtal** [biomedbigdata/namco#46]
Hi, I'm trying to use your web server on my OTU table but I can't seem to upload the dataset. I'm trying to upload an OTU table and a metadata file in .tab format but a "invalid 'row.names' length" pop-up appears whatever I do. It's probably me who's making some silly mistake but I just don't see it

**To Reproduce**
1. Prepare .tab files trying to imitate the [testdata](https://github.com/biomedbigdata/namco/blob/master/app/R/testdata/). They look like this:

```
SampleID	Testvalue
eB1	3
eB2	10
eB3	8
eB4	1
eB7	22
```

```
eB1	eB2	eB3	eB4	eB7	eB8	eB9	eF7	eE5	eF4	eE1	eE7	eF6	eG3	eG6	eE8	eA1	eA4	eA5	eA6	eH3	eE2	eE6	eF3	eH7	eA3	eA7	eC2	eC6	eF2	eF5	eF8	eG1	eG4	eG7	eH5	eF1	eB6	eC5	eC1	taxonomy
4371191	3	10	8	1	22	7	16	12	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas;s__
4479944	0	0	0	0	0	0	0	0	37	11	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	k__Bacteria;p__Actinobacteria;c__MB-A2-108;o__0319-7L14;f__;g__;s__
950120	0	0	0	0	0	0	0	0	0	12	4	11	4	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	k__Bacteria;p__Proteobacteria;c__Deltaproteobacteria;o__Myxococcales;f__Haliangiaceae;g__;s__
```

2. Go to "Upload your OTU/ASV table" at https://exbio.wzw.tum.de/namco/
3. Add both files and press "Upload" button

I've tried adding and removing a header, removing and adding the first column's header, adding a phylogenetic tree, adding quotes... Nothing

**Expected behavior**
No error should pop up

**Screenshots**
![image](https://github.com/biomedbigdata/namco/assets/41147963/956f9ff5-bca6-465f-8da8-24e933c03c26)
![image](https://github.com/biomedbigdata/namco/assets/41147963/03a567ad-8e48-4852-b743-68b55d6f8312)

**Desktop (please complete the following information):**
 - OS: I've tried editing the files from both Windows 10 and Ubuntu 21.10
 - Browser: Firefox

**Comment by alex-d13** [comment]
Hi,

I just used the few lines of your OTU table as input and it worked for me:
[otu.txt](https://github.com/biomedbigdata/namco/files/11541044/otu.txt)
[meta.txt](https://github.com/biomedbigdata/namco/files/11541045/meta.txt)
![image](https://github.com/biomedbigdata/namco/assets/40594032/2c3db330-88a6-411d-840d-4650645a915f)

Do they work for you as well?

Could you maybe share the complete OTU and meta tables? Can also be via email if its sensitive information (alex.dietrich@tum.de).

Best,
Alex

**Comment by silvtal** [comment]
I see. I added the missing fields and also a "OTU" column name for the first column and now it works as expected. I should note that it was not necessary to remove spaces nor characters such as `[`, `]` or `-`.

Thank you so much for the quick response and update!!
