### ISSUE TITLE
Error in Namco's ExBio Tool - Functional Analysis Option

### ISSUE THREAD

**Issue by PumaSocke** [biomedbigdata/namco#47]
Dear Namco Support Team,

I hope this message finds you well. I have been encountering an error while using the functional analysis option in Namco's ExBio tool, and I would greatly appreciate your assistance in resolving this issue.

The specific error message I received states: "Something went wrong with picrust2, not all files were created. Did your FASTA file have the correct OTU/ASV-names?" 
To provide some context, I have ensured that I provided a valid FASTA file as required for the functional analysis. However, despite following the guidelines, the error persists.

To help you understand the issue better, here are some details about my setup:
I am providing the Namcoporject and the used Fasta file in order for you to better understand the issue. 

I kindly request your expertise in troubleshooting and resolving this error. If there are any additional details or logs that would be helpful for you to diagnose the problem, please let me know, and I will be glad to provide them.

Thank you for your time and assistance. I look forward to your response.

Best regards,
Asiri

**Desktop**
 - Windows
 - Browser Chrome 114.0.5735.134
[FunctionalAnalysis_20230703.zip](https://github.com/biomedbigdata/namco/files/11938490/FunctionalAnalysis_20230703.zip)

**Comment by alex-d13** [comment]
Dear User,

Has this problem been fixed?

Best,
Alex
